# Generated by Django 4.1.7 on 2023-04-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_order_id_order_order'),
        ('menu', '0002_rename_cart_id_item_cart_rename_dish_id_item_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dish',
        ),
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
        migrations.AddField(
            model_name='item',
            name='dish',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.dish'),
        ),
    ]
