# Generated by Django 4.1.7 on 2023-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_item_cart_remove_item_dish_item_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
